"""Reviewed snapshot of real routes: unknown routes/files are denied, never auto-granted."""

ROUTE_ACCESS = {
    "WEBSOCKET /ws/stats": "workbench",
    "GET /api/app-info": "disabled",
    "GET /api/update-connectivity/probe": "disabled",
    "GET /api/update-connectivity": "disabled",
    "GET /api/check-update": "disabled",
    "POST /api/update-from-github": "disabled",
    "GET /api/update-backups": "disabled",
    "POST /api/update-rollback": "disabled",
    "GET /api/storage-settings": "admin",
    "PATCH /api/storage-settings": "admin",
    "GET /api/storage-files": "workbench",
    "GET /api/storage-files/{kind}/{rel_path:path}": "workbench",
    "POST /api/storage-files/delete": "workbench",
    "GET /api/asset-classification-prompt": "workbench",
    "PATCH /api/asset-classification-prompt": "admin",
    "GET /api/media-preview": "workbench",
    "GET /api/image-jpeg": "workbench",
    "GET /": "workbench",
    "GET /api/view": "disabled",
    "GET /api/download-output": "workbench",
    "POST /api/smart-canvas/minimax-export": "disabled",
    "POST /api/upload": "disabled",
    "POST /api/ai/upload": "workbench",
    "POST /api/ai/upload-base64": "workbench",
    "POST /api/comfyui/upload-base64": "disabled",
    "POST /api/local-assets/upload": "workbench",
    "POST /api/local-assets/import-urls": "workbench",
    "GET /api/local-assets": "workbench",
    "POST /api/local-assets/folders": "workbench",
    "PATCH /api/local-assets/folders": "workbench",
    "PATCH /api/local-assets/items": "workbench",
    "POST /api/local-assets/delete": "workbench",
    "POST /api/local-assets/move": "workbench",
    "POST /api/local-assets/caption": "workbench",
    "POST /api/local-assets/classify": "workbench",
    "PATCH /api/local-assets/caption": "workbench",
    "POST /api/temp-sh/upload": "disabled",
    "POST /api/cloud-video/upload": "disabled",
    "POST /api/ai/import-local-image": "workbench",
    "GET /api/runninghub/app-info": "disabled",
    "POST /api/runninghub/submit": "disabled",
    "POST /api/runninghub/workflow-submit": "disabled",
    "GET /api/runninghub/workflow-info": "disabled",
    "GET /api/runninghub/workflows": "disabled",
    "GET /api/runninghub/workflows/{workflow_id:path}": "disabled",
    "POST /api/runninghub/workflows/fetch": "disabled",
    "PUT /api/runninghub/workflows/{workflow_id:path}": "disabled",
    "DELETE /api/runninghub/workflows/{workflow_id:path}": "disabled",
    "GET /api/runninghub/query": "disabled",
    "POST /api/runninghub/upload-asset": "disabled",
    "GET /api/codex/status": "disabled",
    "POST /api/codex/help": "disabled",
    "GET /api/gemini-cli/status": "disabled",
    "POST /api/gemini-cli/help": "disabled",
    "GET /api/jimeng/status": "disabled",
    "GET /api/jimeng/credit": "disabled",
    "POST /api/jimeng/logout": "disabled",
    "POST /api/jimeng/login/start": "disabled",
    "GET /api/jimeng/login/status": "disabled",
    "POST /api/jimeng/help": "disabled",
    "POST /api/jimeng/query-media": "disabled",
    "GET /api/config": "workbench",
    "GET /api/models": "workbench",
    "GET /api/providers": "workbench",
    "PUT /api/providers": "admin",
    "GET /api/config/token": "admin",
    "POST /api/providers/test-connection": "admin",
    "POST /api/providers/probe-async": "admin",
    "POST /api/providers/fetch-models": "admin",
    "GET /api/providers/{provider_id}/fetch-models": "admin",
    "POST /api/online-image": "disabled",
    "POST /api/midjourney/submit": "disabled",
    "POST /api/midjourney/actions": "disabled",
    "POST /api/midjourney/modal": "disabled",
    "GET /api/midjourney/tasks/{task_id}": "disabled",
    "POST /api/image-task-query": "disabled",
    "POST /api/canvas-image-tasks": "workbench",
    "GET /api/canvas-image-tasks/{task_id}": "workbench",
    "DELETE /api/canvas-image-tasks/{task_id}": "workbench",
    "POST /api/canvas-image-tasks/{task_id}/refresh": "workbench",
    "POST /api/canvas-comfy-tasks": "disabled",
    "GET /api/canvas-comfy-tasks/{task_id}": "disabled",
    "GET /api/image-params": "workbench",
    "POST /api/canvas-video": "disabled",
    "POST /api/canvas-llm/cancel": "workbench",
    "POST /api/canvas-llm": "workbench",
    "GET /api/conversations": "workbench",
    "POST /api/conversations": "workbench",
    "GET /api/conversations/{conversation_id}": "workbench",
    "DELETE /api/conversations/{conversation_id}": "workbench",
    "GET /api/canvases": "workbench",
    "GET /api/projects": "workbench",
    "POST /api/projects": "workbench",
    "POST /api/projects/{project_id}": "workbench",
    "DELETE /api/projects/{project_id}": "workbench",
    "GET /api/canvases/trash": "workbench",
    "POST /api/canvases": "workbench",
    "GET /api/canvases/{canvas_id}/meta": "workbench",
    "POST /api/canvases/{canvas_id}/meta": "workbench",
    "GET /api/canvases/{canvas_id}": "workbench",
    "POST /api/canvases/{canvas_id}/touch": "workbench",
    "GET /api/canvas-assets": "workbench",
    "GET /api/smart-canvas/prompt-templates": "workbench",
    "POST /api/canvas-assets/check": "workbench",
    "POST /api/canvas-assets/download": "workbench",
    "POST /api/canvas-workflows/export": "workbench",
    "POST /api/canvas-workflows/export-to-library": "workbench",
    "POST /api/asset-library/workflows/upload": "workbench",
    "POST /api/canvas-workflows/import": "workbench",
    "POST /api/smart-canvas/group-export": "workbench",
    "GET /api/asset-library": "workbench",
    "GET /api/prompt-libraries": "workbench",
    "POST /api/prompt-libraries": "workbench",
    "PATCH /api/prompt-libraries/{library_id}": "workbench",
    "DELETE /api/prompt-libraries/{library_id}": "workbench",
    "POST /api/prompt-libraries/items": "workbench",
    "PATCH /api/prompt-libraries/items/{item_id}": "workbench",
    "DELETE /api/prompt-libraries/items/{item_id}": "workbench",
    "POST /api/prompt-libraries/items/delete": "workbench",
    "POST /api/prompt-libraries/categories": "workbench",
    "PATCH /api/prompt-libraries/categories/{category_id}": "workbench",
    "DELETE /api/prompt-libraries/categories/{category_id}": "workbench",
    "POST /api/asset-library/libraries": "workbench",
    "PATCH /api/asset-library/libraries/{library_id}": "workbench",
    "DELETE /api/asset-library/libraries/{library_id}": "workbench",
    "POST /api/asset-library/categories": "workbench",
    "PATCH /api/asset-library/categories/{category_id}": "workbench",
    "DELETE /api/asset-library/categories/{category_id}": "workbench",
    "POST /api/asset-library/items": "workbench",
    "POST /api/asset-library/items/batch": "workbench",
    "GET /api/shared-folders": "admin",
    "POST /api/shared-folders": "admin",
    "DELETE /api/shared-folders/{folder_id}": "admin",
    "GET /api/shared-folders/{folder_id}/tree": "admin",
    "GET /api/shared-folders/{folder_id}/file": "admin",
    "POST /api/shared-folders/import": "admin",
    "PATCH /api/asset-library/items/{item_id}": "workbench",
    "POST /api/asset-library/items/classify": "workbench",
    "POST /api/asset-library/items/{item_id}/register-avatar": "disabled",
    "POST /api/asset-library/items/{item_id}/avatar-status": "disabled",
    "DELETE /api/asset-library/items/{item_id}": "workbench",
    "POST /api/asset-library/items/delete": "workbench",
    "POST /api/asset-library/items/move": "workbench",
    "POST /api/asset-library/items/crop": "workbench",
    "PUT /api/canvases/{canvas_id}": "workbench",
    "POST /api/canvases/{canvas_id}/logs/delete": "workbench",
    "DELETE /api/canvases/{canvas_id}": "workbench",
    "POST /api/canvases/{canvas_id}/restore": "workbench",
    "DELETE /api/canvases/{canvas_id}/purge": "workbench",
    "POST /api/chat": "workbench",
    "POST /api/chat/agent": "disabled",
    "POST /api/chat/stream": "workbench",
    "GET /api/history": "workbench",
    "GET /api/queue_status": "workbench",
    "POST /api/history/delete": "workbench",
    "POST /api/angle/poll_status": "disabled",
    "POST /api/angle/generate": "disabled",
    "POST /generate": "disabled",
    "POST /api/ms/generate": "disabled",
    "POST /api/generate": "disabled",
    "GET /api/comfyui/instances": "admin",
    "PUT /api/comfyui/instances": "admin",
    "GET /api/workflows": "workbench",
    "GET /api/workflows/{name:path}": "workbench",
    "POST /api/workflows": "workbench",
    "PUT /api/workflows/{name:path}/config": "workbench",
    "DELETE /api/workflows/{name:path}": "workbench",
    "POST /api/workflows/{name:path}/run": "disabled"
}

WORKBENCH_STATIC = frozenset([
    '/static/angle.html',
    '/static/comfyui-settings.html',
    '/static/css/instance-ui.css',
    '/static/enhance.html',
    '/static/index.html',
    '/static/js/comfyui-settings.js',
    '/static/js/instance-storage.js',
    '/static/js/instance-ui.js',
    '/static/klein.html',
    '/static/online.html',
    '/static/zimage.html',

    "/static/instance-workspace.html",
    "/static/asset-manager.html",
    "/static/canvas-list.html",
    "/static/canvas.html",
    "/static/css/api-settings.css",
    "/static/css/asset-manager.css",
    "/static/css/canvas-list.css",
    "/static/css/canvas.css",
    "/static/css/comfyui-settings.css",
    "/static/css/image-hover-preview.css",
    "/static/css/smart-canvas.css",
    "/static/css/theme.css",
    "/static/gpt-chat.html",
    "/static/images/RunningHub-B.png",
    "/static/images/RunningHub-W.png",
    "/static/images/dx-os-logo.svg",
    "/static/images/logo.png",
    "/static/images/modelscope-1.gif",
    "/static/images/modelscope.gif",
    "/static/images/volcengine-theme-dark.svg",
    "/static/images/volcengine-theme-light.svg",
    "/static/js/asset-manager.js",
    "/static/js/canvas-list.js",
    "/static/js/canvas-log-cleanup.js",
    "/static/js/canvas.js",
    "/static/js/history-bulk-manager.js",
    "/static/js/i18n-core.js",
    "/static/js/i18n.js",
    "/static/js/i18n/canvas.js",
    "/static/js/i18n/common.js",
    "/static/js/i18n/comfyui-settings.js",
    "/static/js/i18n/api-settings.js",
    "/static/js/i18n/smart-canvas.js",
    "/static/js/i18n/studio.js",
    "/static/js/i18n/validate-i18n.js",
    "/static/js/image-hover-preview.js",
    "/static/js/image-preview.js",
    "/static/js/ltx-director-timeline.js",
    "/static/js/smart-canvas.js",
    "/static/js/theme.js",
    "/static/js/touch-mouse.js",
    "/static/smart-canvas.html",
    "/static/system-prompts/infinite-canvas-prompt-templates.md",
    "/static/vendor/MANIFEST.md",
    "/static/vendor/css/fonts.css",
    "/static/vendor/fonts/inter-1.ttf",
    "/static/vendor/fonts/inter-2.ttf",
    "/static/vendor/fonts/inter-3.ttf",
    "/static/vendor/fonts/inter-4.ttf",
    "/static/vendor/fonts/inter-5.ttf",
    "/static/vendor/fonts/jetbrains-mono-6.ttf",
    "/static/vendor/fonts/jetbrains-mono-7.ttf",
    "/static/vendor/fonts/space-grotesk-10.ttf",
    "/static/vendor/fonts/space-grotesk-8.ttf",
    "/static/vendor/fonts/space-grotesk-9.ttf",
    "/static/vendor/js/lucide.js",
    "/static/vendor/js/tailwindcss-cdn.js",
    "/static/vendor/js/three-0.160.0.module.js",
    "/static/js/instance-session.js",
    "/static/css/instance-login.css"
])

PUBLIC_STATIC = frozenset({"/static/js/instance-login.js", "/static/css/instance-login.css"})
